minsal_catalogo_homepage:
    path:     /hello/{name}
    defaults: { _controller: MinsalCatalogoBundle:Default:index }

minsal_catalogo_new_task:
    path:     /new
    defaults: { _controller: MinsalCatalogoBundle:Default:new }