
# app/config/routing.yml
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
minsal_catalogo:
    resource: "@MinsalCatalogoBundle/Resources/config/routing.yml"
    prefix:   /
